import os
env = Environment()  # Initialize the environment

root_path = os.getcwd()
thirdparty = str(root_path) + "../../thirdparty/"
openflow_common = str(root_path) + "/../common/"

env.Append(CPPPATH = [root_path, openflow_common, thirdparty,
           thirdparty + '/boost/include/',
           thirdparty + '/thrift/include/',
           thirdparty + '/glog/include/',
           thirdparty + '/gflags/include/',
           thirdparty + '/gtest/include/',
           thirdparty + '/sqlite/include/',
           thirdparty + '/tinyxml/'
           ])

env.Append(LIBPATH = [openflow_common,
           thirdparty + '/boost/lib/',
           thirdparty + '/thrift/lib',
           thirdparty + '/glog/lib',
           thirdparty + '/gflags/lib',
           thirdparty + '/gtest/lib',
           thirdparty + '/sqlite/lib',
           thirdparty + '/tinyxml',
           root_path + "/rpc/master",
           root_path + "/rpc/agent",
           ])

env.Append(LIBS = ['common', 'thrift', 'glog', 'gflags', 'gtest'
           ,'sqlite3', 'tinyxml', 'boost_thread', 'boost_system'
           ,'pthread', 'dl', 'z'])

env.Append(LINKFLAGS = ['-static'])

env.Append(CCFLAGS = ['-Wall', '-O2', '-g', '-Wno-unused-but-set-variable'
                      ,'-Wno-unused-parameter', '-Wno-unused-local-typedefs'
                      ,'-Wno-missing-field-initializers','-DTIXML_USE_STL'])
Export('env')

SConscript(['boost/simple/SConscript'], exports = 'env')
SConscript(['boost/parseXML/SConscript'], exports = 'env')
SConscript(['boost/thread/SConscript'], exports = 'env')
SConscript(['mysql/SConscript'], exports = 'env')
SConscript(['sqlite/simple/SConscript'], exports = 'env')
SConscript(['sqlite/save_xml/SConscript'], exports = 'env')
