Import('env')

env.Prepend(LIBS = ['master', 'agent'])

env.Program(
    target = "deque_test",
    source = ['deque_test.cpp']
)

SConscript(['master_client/SConscript'], exports = 'env')
SConscript(['agent_client/SConscript'], exports = 'env')
