import os
env = Environment()  # Initialize the environment

root_path = os.getcwd()
thirdparty = str(root_path) + "/../thirdparty/"

env.Append(CPPPATH = [root_path, thirdparty,
           thirdparty + '/boost/include/',
           thirdparty + '/glog/include/',
           thirdparty + '/gflags/include/',
           thirdparty + '/gtest/include/',
           thirdparty + '/sqlite/include/',
           ])

env.Append(LIBPATH = [thirdparty + '/boost/lib/',
           thirdparty + '/glog/lib',
           thirdparty + '/gflags/lib',
           thirdparty + '/gtest/lib',
           thirdparty + '/sqlite/lib/',
           ])

env.Append(LIBS = ['boost_system', 'glog', 'gflags', 'sqlite3'
           , 'boost_filesystem', 'boost_thread', 'boost_system', 'boost_date_time'])

env.Append(CCFLAGS = ['-Wall', '-O2', '-g', '-Wno-unused-but-set-variable'
           , '-Wno-unused-parameter', '-Wno-unused-local-typedefs'
           , '-Wno-missing-field-initializers'])

env.Append(LINKFLAGS = ['-static'])

env.Library(
    target = "common",
    source = [
    "sqlite_table.cpp",
    "sqlite_db.cpp",
    "dataset.cpp",
    "main_template.cpp",
    "utils.cpp",
    ],
)

