Import('env')

env.Append(CPPPATH = '/usr/include/mysql/')
env.Append(LIBPATH = '/usr/lib/mysql/')
env.Append(LIBS = 'mysqlclient')

env.Program(
    target = 'play_xml',
    source = 'play_xml.cpp'
)

